kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: true
  ignore_unconnected: false

outputs:
  # For more information: https://github.com/INTI-CMNB/KiBoM
  - name: 'print schema'
    comment: "Print schematic (PDF)"
    type: pdf_sch_print
    dir: docs
