on: [push, pull_request]

jobs:
  gerbers:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: mkdir -p output
      run: mkdir -p output
    - name: kicad-exports -c gerbers.kibot.yaml
      uses: nerdyscout/kicad-exports@v2.2
      with:
        config: config/gerbers.kibot.yaml
        dir: output/
        board: '*.kicad_pcb'
        schema: '*.sch'
    - name: "check output: gerber"
      run: |
        test -f output/gerbers/*B_CrtYd.gbr && \
        test -f output/gerbers/*F_CrtYd.gbr && \
        test -f output/gerbers/*B_Cu.gbr && \
        test -f output/gerbers/*F_Cu.gbr && \
        test -f output/gerbers/*B_Mask.gbr && \
        test -f output/gerbers/*F_Mask.gbr && \
        test -f output/gerbers/*B_Paste.gbr && \
        test -f output/gerbers/*F_Paste.gbr && \
        test -f output/gerbers/*B_SilkS.gbr && \
        test -f output/gerbers/*F_SilkS.gbr && \
        test -f output/gerbers/*B_CrtYd.gbr && \
        test -f output/gerbers/*F_CrtYd.gbr
    - name: "check output: gerber"
      run: |
        test -f output/gerbers/*-NPTH_drill.gbr && \
        test -f output/gerbers/*-NPTH_drill.drl && \
        test -f output/gerbers/*-PTH_drill.gbr && \
        test -f output/gerbers/*-PTH_drill.drl
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/gerbers
    - run: zip -r output/gerbers output/gerbers
    - name: Upload gerbers
      id: upload-gerbers
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./output/gerbers.zip
        asset_name: gerbers.zip
        asset_content_type: application/zip
    - run: find output/
    - name: Upload In1.Cu
      id: upload-in1-cu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./output/svgs/gt9113_breakout_rev-In1_Cu.svg
        asset_name: In1_Cu.svg
        asset_content_type: image/svg+xml
    - name: Upload In2.Cu
      id: upload-in2-cu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: output/svgs/gt9113_breakout_rev-In2_Cu.svg
        asset_name: In2_Cu.svg
        asset_content_type: image/svg+xml

    - run: zip -r output/svgs output/svgs
    - name: Upload all SVGs
      id: upload-all-svgs
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: output/svgs.zip
        asset_name: all_svgs.zip
        asset_content_type: application/zip

  plot:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c plot.kibot.yaml
      uses: nerdyscout/kicad-exports@v2.2
      with:
        config: config/plot.kibot.yaml
        dir: output/
        schema: '*.sch'
        board: '*.kicad_pcb'
    - name: "check output: plot"
      run: |
        test -f 'output/docs/img/gt9113_breakout-top.svg' && \
        test -f 'output/docs/img/gt9113_breakout-bottom.svg'
    - uses: actions/upload-artifact@v2
      if: ${{ success() }}
      with:
        name: ${{ github.job }}
        path: output/docs/img
    - name: Upload top svg
      id: upload-top-svg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: 'output/docs/img/gt9113_breakout-top.svg'
        asset_name: top.svg
        asset_content_type: image/svg+xml
    - name: Upload bottom svg
      id: upload-bottom-svg
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: 'output/docs/img/gt9113_breakout-bottom.svg'
        asset_name: bottom.svg
        asset_content_type: image/svg+xml

  release:
    name: Make release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_id }}
          release_name: Release ${{ github.run_id }} (${{ github.sha }})
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
